### ISSUE TITLE
Laboratory Work #0

### ISSUE THREAD

**Issue by Ryvcy** [OS-IS/ai202-pogorelov#1]

**Comment by Ryvcy** [comment]
![image](https://github.com/user-attachments/assets/d90f3763-98b8-4c50-901d-202b95f18c11)

**Comment by Ryvcy** [comment]
![image](https://github.com/user-attachments/assets/53d622c9-5317-4d73-9b2e-43150d90722b)
Не знаю у чому тут проблема

**Comment by Ryvcy** [comment]
![image](https://github.com/user-attachments/assets/3ef40f5c-3480-432a-848e-bf4893617193)
Мені не надається доступ

**Comment by Ryvcy** [comment]
![image](https://github.com/user-attachments/assets/9f813089-9a45-4700-8a28-ab78bb5003ad)

**Comment by Ryvcy** [comment]
![image](https://github.com/user-attachments/assets/9b618c65-76f8-4be5-8fb8-be3870139f00)

**Comment by oleksandrblazhko** [comment]
Оцінка = 5 балів
