### ISSUE TITLE
Control Work # 0

### ISSUE THREAD

**Issue by oleksandrblazhko** [OS-IS/ai202-pogorelov#4]
Правильна відповідь на контрольне запитання дозволить вам отримати додаткові 2 бали 
до балів за виконання лабораторної роботи, якщо ви виявите бажання надати таку відповідь.
Відповідайте на запитання через коментар.

Запитання
11) Відомо, що всі сучасні засоби аутентифікації використовують комбінацію 
щонайменше двох з трьох класів: «те, що знаю», «те, чим володію», «те, чим є». 
Вкажіть, будь ласка, які два класи використовуються 
для безпечної взаємодії з GitHub-сервером та обґрунтуйте свій вибір.

**Comment by Ryvcy** [comment]
Для безпечної взаємодії з GitHub-сервером використовуються __пароль__ або __токен доступу__ ("Те, що знаю") та __апаратний ключ__ або __двофакторна аутентифікація за номером телефону__ чи __електронною поштою__ ("Те, чим володію"). 

- Пароль чи токен є основним засобом аутентифікації, який дозволяє ідентифікувати користувача.

- Двофакторна аутентифікація додає другий рівень захисту, вимагаючи від користувача підтвердити свою особу за допомогою апаратного пристрою або мобільного телефону.

Ця комбінація є найдіною та значно підвищує рівень безпеки, зменшуючи ймовірність несанкціонованого доступу.

**Comment by oleksandrblazhko** [comment]
2 бали
